### ISSUE TITLE
“Loading… ” message appearing on web page when the dash app is run on django

### ISSUE THREAD

**Issue by yash7867** [GibbsConsulting/django-plotly-dash#134]
Hi,

After running dash app several times , the “loading…” message is appearing on the web page.

Please help in resolving this issue.

**Comment by GibbsConsulting** [comment]
@yash7867 to investigate an issue, some more information is needed in order to be able to reproduce it. Ideally, this reproduction will enable the steps taken from an initial working installation. There are some notes [here](https://django-plotly-dash.readthedocs.io/en/latest/development.html#bug-reporting) also.

In this particular case, however, you might want to take a look at #126 and #127 as this could well be what is underlying this particular problem.

**Comment by yash7867** [comment]
Hi i tried installing the latest versions of dash,  dash-core-components, dash-html-components, dash-bootstrap-components, dash-renderer etc and running the dash app but the issue is still seen

**Comment by yash7867** [comment]
Loading issue is resolved now. 
Faced following two issues 

**Issue 1 :**

The statement **" target_id = '{}.{}'.format(output['id'], output['property']) "**  in **def dispatch_with_args(self, body, argMap)** method of **dash_wrapper.py file throws error that String indices should be integers and not string** 

Added one print statement to see what **'output'** contains 
**Body is :  {'output': 'demomap.figure', 'inputs': [{'id': 'table', 'property': 'selected_rows'}]}** ---> print statement written in **def dispatch_with_args(self, body, argMap)** method of **dash_wrapper.py** file 

Because of this error graphs were not getting displayed. Hence, following changes were made in **def dispatch_with_args(self, body, argMap)** method of dash_**wrapper.py file**

**Solution**
        **try:**
            target_id = '{}.{}'.format(output['id'], output['property']) 
        **except Exception as e:**
            target_id = output
 

**Issue 2:**

The output was getting displayed only on part of the screen. To show the output on the entire screen following small code change was done in **plotly_dash.py** file 

**Solution**
**ratio = 0.1 -----> ratio = 1.0**
def plotly_app(context, name=None, slug=None, da=None, **ratio=1.0**, use_frameborder=False, initial_arguments=None):

**Comment by yash7867** [comment]
So changes are in library files

**Comment by lhy1149** [comment]
Hi, I'm afraid loading issue is **NOT** resolved 

**if da and da.have_current_state_entry(output['id'], output['property']):** still failed
all references to output in this method is assumed a dict, but in what condition output is a str? 

It' seems like when used in django, there is a problem

Is django-plotly-dash need a flask server to run dash app? may be not, cause when I run demo,
the live updating example show a graph. Can anybody pay attention to this issue, because if this lib can't run it in Django, it doesn't make sense.

**Comment by yash7867** [comment]
Loading issue is resolved for me

**Comment by GibbsConsulting** [comment]
@lhy1149 are you using the latest version (v0.9.9) of django-plotly-dash? If so then you may have found a new problem which is best handled in a new issue.

If so, you might like to know that there is a brief description [here](https://django-plotly-dash.readthedocs.io/en/latest/development.html#bug-reporting) of what makes a useful bug report.

I will mark this issue closed as @yash7867 reports it resolved.
